@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentTypeValue = application/json


### List all messages
GET {{host}}/msg


### Post new message
POST {{host}}/msg
Content-Type: {{contentTypeValue}}

{
  "payload": "New message created"
}


### Get a message
GET {{host}}/msg/8e8439fa-b3e2-4fb5-8a1f-6307d7e19f3c