@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentTypeValue = application/json


### List all messages
GET {{host}}/msg


### Post new message
POST {{host}}/msg
Content-Type: {{contentTypeValue}}

{
  "payload": "Hi, new message created"
}


### Get a message
GET {{host}}/msg/5c97fde3-0221-4ca5-bab0-4422e78204dd