@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentTypeValue = application/json


### List all messages
GET {{host}}/msg


### Post new message
POST {{host}}/msg
Content-Type: {{contentTypeValue}}

{
  "payload": "Hi There",
  "size": 86
}


### Get a message
GET {{host}}/msg/340